✨ 3dmaskave_grp: regexp mask

diff --git a/3dmaskave_grp b/3dmaskave_grp
--- a/3dmaskave_grp
+++ b/3dmaskave_grp
@@ -33,6 +33,9 @@ $(basename $0) -csv dlpfc.csv -mask "mask.nii.gz" -- paths/to/1*_2*/inputs.nii.g
 3dmaskave_grp -csv MPFC-ACC_1.csv -m "ACC=mask.nii.gz" -m "PFC=mask_many.nii.gz<3>" -- paths/to/1*_2*/inputs.nii.gz
 
   -m|-mask NAME=MASK    input mask optionally with afni selector
+                        MASK can also be a perl regular expression like 's:search:replace:'
+                        -m tian_nacc.core='s:[^/]*:warps/tian_nacc_rs.nii.gz<1>:'
+
   -csv  FILE            save csv as FILE (defaults to NAME.csv)
   -datatable FILE       use datatable as input. req Subj is first and InputFile last col
   -label_col IDX        req. for datatable. what col index to use for labels
@@ -105,11 +108,31 @@ parse_args(){
    return 0
 }
 
+# check if we input something like s:patt:replace:
+name_is_regex(){
+   # start like s/ or s:
+   [[ "$*" =~ ^s([/:]) ]] &&
+   # ends with the same search delim but optionally 'g' or 'i'
+   [[ "$*" =~ ${BASH_REMATCH[1]}[gi]*$ ]]
+}
+
+# analgous to 'test -r $mask' but works for '$file<roinum>' AFNI syntax
+# abstracted from check_mask so we can use if mask is a regexp
+check_roi() {
+   mask="${1:?input mask<roi> to confirm count is nonzero}"
+   maskval=$(3dmaskave -q -mask "$mask" "$mask" 2>/dev/null|| echo 0)
+   [[ $maskval == 0 ]] && warn "ERROR:BAD MASK: '$mask'" && return 1
+   return 0
+}
+
+# wrap check_roi with 3dcalc and regexp checks
 check_mask() {
    mask="$1"
    [[ $mask =~ ^3dcalc ]] && warn "WARNING: inline 3dcalc will be run for each input file!" && return 0
-   maskval=$(3dmaskave -q -mask "$mask" "$mask" 2>/dev/null|| echo 0)
-   [[ $maskval == 0 ]] && warn "ERROR:BAD MASK: '$mask'" && return 1
+   name_is_regex "$mask" &&
+      warn "WARNING: using regexp mask '$mask'. cannot preemptivly check if mask exists" &&
+      return 0
+   check_roi "$mask"
    return 0
 }
 
@@ -188,6 +211,13 @@ maskave_csv() {
    id="$1"; shift
 
    already_exists "$mask_name,$id,$input_name," && return 0
+   if name_is_regex "$mask_file"; then
+      local regexp="$mask_file"
+      mask_file=$(perl -plne "$regexp" <<< "$cfile")
+      ! check_roi "$mask_file"  &&
+         echo "ERROR: mask regexp applied but '$mask_file' doesnt exist or roi is empty. see: perl -pne '$regexp' <<< '$cfile'" >&2 &&
+         return 1
+   fi
 
    val="$(maskave_NA "$mask_file" "$cfile")"
    echo "${mask_name},${id},${input_name},${val}"
