✨ 4dConcatSubBriks: add command switches(-p pattern, -a for afni, -h help)

diff --git a/4dConcatSubBriks b/4dConcatSubBriks
--- a/4dConcatSubBriks
+++ b/4dConcatSubBriks
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 set -euo pipefail
 trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT
+env | grep -q ^NOAFNI= || NOAFNI=1
 
 # wrap around 3dbucket and 3drefit
 # extract a subbrick from a list of nifti 
@@ -14,11 +15,35 @@ trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT
 #   3) [optional] sub brick (0 if not provided)
 # env
 #  NOAFNI=1 4dConcatSubBricks prefix 'glob' # NOAFNI=1 will skip opening anfi and generating outliers
+usage(){
+  cat >&2 <<HEREDOC
+look at a single brick accross subjects
+USAGE:
+  $(basename $0) [options] output.nii.gz 'gl*ob' [subbrik]"
 
-[ $# -lt 2 ] && 
-  echo -e "look at a single brick accross subjects\nUSAGE: $0 output.nii.gz 'gl*ob' [subbrik]" >&2 &&
+OPTIONS: (are optional)
+ -a                # show afni afteward
+ -p '\d{5}_\d{8}'  # change id pattern
+ -h                # this help
+
+ARGUMENTS:
+ output.nii.gz - final file to create
+ 'gl*ob' - file glob matching all images to concat. MUST BE QUOTED
+ subbrik (optional) specify with volume of each globbed file to use
+HEREDOC
   exit 1
-  [ $# -gt 3 ] && echo "too many input argumetns ($#)! did you put single quotes around the 'gl*ob'?" >&2 && exit 1
+}
+
+[ $# -lt 2 ] && usage
+PATTERN='\d{5}_\d{8}'
+case $1 in
+  -p) PATTERN="$2"; shift 2;;
+  -a) NOAFNI=""; shift;;
+  -h) usage;;
+   *) ;; # nothing to do. will use stuff later
+esac
+
+[ $# -gt 3 ] && echo "too many input argumetns ($#)! did you put single quotes around the 'gl*ob'?" >&2 && exit 1
 
 prefix="$1"; shift
 glob="$1"; shift
@@ -27,8 +52,8 @@ glob="$1"; shift
 ! [[ $prefix =~ nii$|nii.gz$|.HEAD$ ]] && echo "prefix '$prefix' must end in .nii, .nii.gz, or .HEAD" && exit 1
 [ -z "$(ls $glob)" ] && echo "bad glob provided ($glob). consider .HEAD?" >&2 && exit 1
 
-ids="$(ls $glob | perl -lne 'print $& if m/\d{5}_\d{8}/')"
-[ -z "$ids" ] && echo "could not find lunaid(_date) in provided glob" >&2 && exit 1
+ids="$(ls $glob | grep -Po "$PATTERN")"
+[ -z "$ids" ] && echo "could not find ID using pattern '$PATTERN' in provided glob '$glob'" >&2 && exit 1
 
 
 if [ ! -r "$prefix" ]; then
@@ -40,7 +65,7 @@ else
    echo "rm $prefix # to regenerate; skipping 3dbucket and 3drefit"
 fi
 
-env | grep NOAFNI && exit 0
+[ -n "$NOAFNI" ] && exit 0
 
 afni -com 'OPEN_WINDOW axialgraph' "$prefix"  >/dev/null 2>&1
 
