allow just lunaid in ids

diff --git a/4dConcatSubBriks b/4dConcatSubBriks
--- a/4dConcatSubBriks
+++ b/4dConcatSubBriks
@@ -25,8 +25,8 @@ glob="$1"; shift
 
 [ -z "$(ls $glob)" ] && echo "bad glob provided ($glob). consider .HEAD?" >&2 && exit 1
 
-ids="$(ls $glob | perl -lne 'print $& if m/\d{5}_\d{8}/')"
-[ -z "$ids" ] && echo "could not find lunaid_date in provided glob" >&2 && exit 1
+ids="$(ls $glob | perl -lne 'print $& if m/\d{5}(_\d{8})?/')"
+[ -z "$ids" ] && echo "could not find lunaid(_date) in provided glob" >&2 && exit 1
 
 if [ ! -r "$prefix" ]; then
    echo "3dbucket: combine"
