✨ gitver: file specific info; use in tat2

diff --git a/gitver b/gitver
--- a/gitver
+++ b/gitver
@@ -2,30 +2,41 @@
 set -euo pipefail
 
 # get current git sha of a provided script (full path or in $PATH)  or directory
-# EXAMPLE: (by (1) app in path, (2) file, (3) directory)
-#  gitver gitver                          # e45891c
-#  gitver /opt/ni_tools/lncdtools/gitver  # e45891c
-#  gitver /opt/ni_tools/lncdtools         # e45891c
+# looks like 78341f2:2023-07-21:1,1(+),3(-)
+#
+# EXAMPLE: (by (1) directory (2) fullpath (3+4) app in path )
+#  gitver /opt/ni_tools/lncdtools         # 4d99a09:2023-07-24:2,8(+),5(-)
+#  gitver /opt/ni_tools/lncdtools/gitver  # dc2e48c:2021-08-09:1,7(+),2(-)
+#  gitver gitver                          # dc2e48c:2021-08-09:1,7(+),2(-)
+#  gitver dryrun                          # cc2097f:2022-10-11:
+#  gitver /tmp                            # git:NA
+
 # 20200909WF - init
+# 20230804WF - given file, ouput log+diff specific to file
 
 # what to spit out when error/no git repo
-nover=NA
+nover=git:NA
+file=""
 
-if [ $# -eq 1 ]; then 
+if [ $# -eq 1 ]; then
    repo="$1"
    # try script if not file
-   [ ! -r "$repo" ] && repo="$(which "$repo")"
+   [ ! -r "$repo" ] && repo="$(which "$repo")" || :
    # if given a file, use directory
-   [ -r "$repo" -a ! -d "$repo" ] && repo="$(dirname "$repo")"
+   if [ -r "$repo" -a ! -d "$repo" ]; then
+      file="-- $repo"
+      repo="$(dirname "$repo")"
+   fi
    if [ ! -d "$repo" ]; then
-      echo "# ERROR: bad dir $repo" >&2
+      echo "# ERROR: gitver given bad dir/file/app: '$1'" >&2
       echo $nover
       exit 1
    fi
    cd "$repo"
 fi
+
 if git rev-parse --short HEAD >/dev/null 2>&1; then
-   echo $(git log -1 --pretty=format:%h:%as):$(git diff --shortstat|tr -d '[a-z ]')
+   echo $(git log -1 --pretty=format:%h:%as $file):$(git diff --shortstat $file|tr -d '[a-z ]')
 else
    echo $nover
 fi
