✨ maskvolume: can take other 3dROIstats switches

diff --git a/maskvolume b/maskvolume
--- a/maskvolume
+++ b/maskvolume
@@ -1,13 +1,27 @@
 #!/usr/bin/env bash
-# 20230131WF - quick look at roi volume (mm^3)
 # use 3dROIstats nzvolume with mask as own input. reformat and transpose
 # columns are
 # ROI# VOLUME(mm)
+#
+# 20230131WF - quick look at roi volume (mm^3)
+# 20231218WF - add usage and allow other 3dROIstats switches
+
+case $1 in
+   --help*|-h*)
+      echo "USAGE: $0 [-nzvoxels|-nzmean|-nzvolume] atlas.nii.gz"; exit;;
+   -*) measure="$1"; title="${measure/\-/}"; shift;;
+   *) measure="-nzvolume"; title="Volume_mm3";;
+esac
+
+[ ! -r "${1:?roi file to report mask volume}" ] &&
+   warn "ERROR: cannot read $1" && exit 1
+[ $# -gt 1 ] &&
+   warn "ERROR: $0 given more than one input ($# != 1)" && exit 1;
+
 
 # NB. removed neat bash trick: "$1"{,}  same as  "$1" "$1"
-
-echo -e "#ROI\tVolume_mm3"
-3dROIstats -1Dformat -nomeanout -nzvolume -mask "$1" "$1"|
- sed '2s/#//;s/\.0\+//g;s/Volume_//g;s/^\t\+//'|
+echo -e "#ROI\t$title"
+3dROIstats -1Dformat -nomeanout "$measure" -mask "$1" "$1"|
+ sed '2s/#//;s/\.0\+//g;s/[A-Za-z0-9]\+_//g;s/^\t\+//'|
  grep -v '#'|
  datamash transpose
