✅ tests for mknii and niinote; update tat2 test

diff --git a/mknii b/mknii
--- a/mknii
+++ b/mknii
@@ -7,7 +7,7 @@ env | grep ^DRYRUN= && DRYRUN=echo || DRYRUN=""
 #
 usage() {
 cat <<HEREDOC
-$(basename "$0") path/to/dcm/ output.nii.gz
+$(basename "$0") output.nii.gz path/to/dcm/
 
    first argument must be a folder or single dicom
    escape spaces in input.
@@ -27,12 +27,14 @@ HEREDOC
 #  20201016WF  init
 
 [ $# -ne 2 ] && usage
-dcm_folder="$1"; shift
 nii_out="$1"; shift
+dcm_folder="$@"; shift
 [ -r "$nii_out" ] && echo "# have '$nii_out'" && exit 0
 [ -r "${nii_out/magnitude.nii.gz/magnitude1.nii.gz}" ] && echo "# have magnitude1.nii.gz, considering that the same as '$nii_out'" && exit 0
 [ ${nii_out:(-7)} != ".nii.gz" ] && echo "output must have .nii.gz extention!" && exit 1
-[ ! -r "$dcm_folder"  ] && echo "# missing '$dcm_folder'" && exit 1
+
+# should let dcm2niix just fail instead of doing the work here?
+[ $(ls "$dcm_folder" -type f,l -print -quit|wc -l) -gt 0  ] && echo "# '$dcm_folder' DNE or is empty?" && exit 1
 
 outname="$(basename "$nii_out" .nii.gz)"
 outdir="$(dirname "$nii_out")"
@@ -66,4 +68,7 @@ if [ ! -r "$nii_out" ]; then
    exit 1
 fi
 
+# 3dNotes likes to complain. silence it
+export AFNI_NIFTI_TYPE_WARN=NO
+export AFNI_NO_OBLIQUE_WARNING="YES"
 $DRYRUN 3dNotes -h "$0 $dcm_folder $nii_out" "$nii_out" 
